name: Angular Dev Deploy

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: ap-east-1                # Change to your region
  BUCKET_NAME: my-angular-app-dev      # Your S3 bucket for dev
  DISTRIBUTION_ID: CLOUDFRONT_DIST_ID  # CloudFront dist ID for dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Angular dev build
        run: npm run build -- --configuration development

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: aws s3 sync dist/<your-project-name>/ s3://$BUCKET_NAME --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
